#!/usr/bin/env bash

release_tag=${RELEASE_TAG:-$GITHUB_REF_NAME}
preview=""
if [[ "$release_tag" == *"-pre" ]]; then
    preview="-p"
fi

gh release view "$release_tag" ||\
    gh release create -t "$release_tag" -d "$release_tag" -F "$1" $preview
