name: CI

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  clippy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: ./script/clippy

  tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest
      - run: cargo nextest run --workspace --no-fail-fast --no-tests=warn

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Install Linux dependencies
        run: ./script/linux
      - name: Download WASI SDK
        run: ./script/download-wasi-sdk
      - run: cargo build -p flint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
